### ISSUE TITLE
Possible 4.3-dev3 issue

### ISSUE THREAD

**Issue by suni-masuno** [Portponky/better-terrain#72] opened 2024-02-13 01:18 UTC
I'm playing with a toy project in 4.3-dev3 and went to install your plugin. (which rocks, btw) But I don't see the terrain option at the bottom when selecting a tileset. I do see some interesting errors sometimes though while installing.

<details>
  <summary>screenshot...</summary>
![image](https://github.com/Portponky/better-terrain/assets/24526738/2f52a960-c82c-4c85-9c0e-d7d92c3626b4)
</details>

<details>
  <summary>and the output is...</summary>
```
Godot Engine v4.3.dev3.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
  res://addons/better-terrain/editor/TerrainProperties.gd:68 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainProperties.gd:92 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2793 - Failed to load script "res://addons/better-terrain/editor/TerrainProperties.gd" with error "Parse error". (User)
  res://addons/better-terrain/editor/TerrainEntry.gd:106 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainEntry.gd:129 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainEntry.gd:137 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainEntry.gd:151 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2793 - Failed to load script "res://addons/better-terrain/editor/TerrainEntry.gd" with error "Parse error". (User)
  res://addons/better-terrain/editor/Dock.gd:125 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:125 - Parse Error: Cannot infer the type of "pick" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/Dock.gd:127 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:139 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:143 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:155 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:162 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:162 - Parse Error: Cannot infer the type of "terrain_count" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/Dock.gd:165 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:165 - Parse Error: Cannot infer the type of "terrain" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/Dock.gd:170 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:170 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:170 - Parse Error: Cannot infer the type of "terrain" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/Dock.gd:230 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:247 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:248 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:271 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:288 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:291 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:307 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:329 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:329 - Parse Error: Cannot infer the type of "t" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/Dock.gd:330 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:394 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:394 - Parse Error: Cannot infer the type of "t" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/Dock.gd:414 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:438 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:443 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:444 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:445 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:450 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:452 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:464 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:466 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:468 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:482 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:484 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:485 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:491 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:524 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:536 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:536 - Parse Error: Cannot infer the type of "terrain" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/Dock.gd:562 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:573 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:609 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:611 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:615 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:624 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:626 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:630 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:643 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:677 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:679 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:683 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:692 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:694 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/Dock.gd:698 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2793 - Failed to load script "res://addons/better-terrain/editor/Dock.gd" with error "Parse error". (User)
  res://addons/better-terrain/editor/TerrainUndo.gd:11 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:52 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:76 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:76 - Parse Error: Cannot infer the type of "tile_type" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TerrainUndo.gd:77 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:81 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:82 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:83 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:104 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:104 - Parse Error: Cannot infer the type of "tile_type" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TerrainUndo.gd:105 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:110 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:110 - Parse Error: Cannot infer the type of "terrain" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TerrainUndo.gd:111 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:113 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:122 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:123 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:132 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:132 - Parse Error: Cannot infer the type of "tile_type" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TerrainUndo.gd:136 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:137 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:138 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:148 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:151 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:151 - Parse Error: Cannot infer the type of "types" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TerrainUndo.gd:153 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:155 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:157 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:161 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:164 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TerrainUndo.gd:172 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2793 - Failed to load script "res://addons/better-terrain/editor/TerrainUndo.gd" with error "Parse error". (User)
  res://addons/better-terrain/editor/TileView.gd:12 - Parse Error: Preload file "res://addons/better-terrain/icons/paint-symmetry/SymmetryMirror.svg" does not exist.
  res://addons/better-terrain/editor/TileView.gd:13 - Parse Error: Preload file "res://addons/better-terrain/icons/paint-symmetry/SymmetryFlip.svg" does not exist.
  res://addons/better-terrain/editor/TileView.gd:14 - Parse Error: Preload file "res://addons/better-terrain/icons/paint-symmetry/SymmetryReflect.svg" does not exist.
  res://addons/better-terrain/editor/TileView.gd:15 - Parse Error: Preload file "res://addons/better-terrain/icons/paint-symmetry/SymmetryRotateClockwise.svg" does not exist.
  res://addons/better-terrain/editor/TileView.gd:16 - Parse Error: Preload file "res://addons/better-terrain/icons/paint-symmetry/SymmetryRotateCounterClockwise.svg" does not exist.
  res://addons/better-terrain/editor/TileView.gd:17 - Parse Error: Preload file "res://addons/better-terrain/icons/paint-symmetry/SymmetryRotate180.svg" does not exist.
  res://addons/better-terrain/editor/TileView.gd:18 - Parse Error: Preload file "res://addons/better-terrain/icons/paint-symmetry/SymmetryRotateAll.svg" does not exist.
  res://addons/better-terrain/editor/TileView.gd:19 - Parse Error: Preload file "res://addons/better-terrain/icons/paint-symmetry/SymmetryAll.svg" does not exist.
  res://addons/better-terrain/editor/TileView.gd:30 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:30 - Parse Error: Cannot infer the type of "paint" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TileView.gd:31 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:31 - Parse Error: Cannot infer the type of "paint_symmetry" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TileView.gd:148 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:148 - Parse Error: Cannot infer the type of "type" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TileView.gd:149 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:155 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:155 - Parse Error: Cannot infer the type of "terrain" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TileView.gd:158 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:159 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:373 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:373 - Parse Error: Cannot infer the type of "type" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TileView.gd:374 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:378 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:378 - Parse Error: Cannot infer the type of "terrain" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TileView.gd:383 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:386 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:386 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:392 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:392 - Parse Error: Cannot infer the type of "paint_terrain" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TileView.gd:393 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:394 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:395 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:418 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:479 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:545 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:545 - Parse Error: Cannot infer the type of "paint_terrain" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TileView.gd:547 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:562 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:564 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:565 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:577 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:579 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:580 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:590 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:590 - Parse Error: Cannot infer the type of "type" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TileView.gd:591 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:591 - Parse Error: Cannot infer the type of "goal" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TileView.gd:593 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:594 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:603 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:715 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:718 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:719 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:721 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:722 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:724 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:727 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:728 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:744 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:751 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:753 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:763 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:796 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:797 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:818 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:818 - Parse Error: Cannot infer the type of "type" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TileView.gd:819 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:819 - Parse Error: Cannot infer the type of "goal" variable because the value doesn't have a set type.
  res://addons/better-terrain/editor/TileView.gd:822 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:824 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:833 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:839 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:841 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:843 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:849 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:851 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:853 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:858 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:860 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:861 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:863 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:868 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:870 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:871 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:871 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/editor/TileView.gd:873 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2793 - Failed to load script "res://addons/better-terrain/editor/TileView.gd" with error "Parse error". (User)
  res://addons/better-terrain/BetterTerrainData.gd:29 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:30 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:31 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:32 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:38 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:39 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:40 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:41 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:47 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:28 - Parse Error: Assigned value for constant "symmetry_mapping" isn't a constant expression.
  res://addons/better-terrain/BetterTerrainData.gd:63 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:66 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:68 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:69 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:72 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:74 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:76 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:78 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:82 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:84 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:86 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:88 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:455 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:457 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:458 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:462 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:463 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:466 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:467 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:470 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:471 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:474 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  res://addons/better-terrain/BetterTerrainData.gd:475 - Parse Error: Identifier "BetterTerrain" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2793 - Failed to load script "res://addons/better-terrain/BetterTerrainData.gd" with error "Parse error". (User)
  scene/resources/resource_format_text.cpp:448 - res://addons/better-terrain/editor/Dock.tscn:7 - ext_resource, invalid UID: uid://b0es228gfcykd - using text path instead: res://addons/better-terrain/icons/Warning.svg
  Resource file not found: res://addons/better-terrain/icons/Warning.svg (expected type: Texture2D)
  scene/resources/resource_format_text.cpp:448 - res://addons/better-terrain/editor/Dock.tscn:14 - ext_resource, invalid UID: uid://baxhjy28r1iqj - using text path instead: res://addons/better-terrain/icons/SymmetryRotateClockwise.svg
  Resource file not found: res://addons/better-terrain/icons/SymmetryRotateClockwise.svg (expected type: Texture2D)
  scene/resources/resource_format_text.cpp:448 - res://addons/better-terrain/editor/Dock.tscn:15 - ext_resource, invalid UID: uid://csbwdkr6bc2db - using text path instead: res://addons/better-terrain/icons/SymmetryRotateCounterClockwise.svg
  Resource file not found: res://addons/better-terrain/icons/SymmetryRotateCounterClockwise.svg (expected type: Texture2D)
  scene/resources/resource_format_text.cpp:448 - res://addons/better-terrain/editor/Dock.tscn:17 - ext_resource, invalid UID: uid://b7fx4mk18lmls - using text path instead: res://addons/better-terrain/icons/SymmetryRotateAll.svg
  Resource file not found: res://addons/better-terrain/icons/SymmetryRotateAll.svg (expected type: Texture2D)
```
</details>

Of course I could just be doing something silly today. Sorry if it's a false alarm or something.

**Comment by Portponky** [comment] 2024-02-19 15:19
Hi, have you tried restarting Godot? Its plugin initialization is a bit funny at runtime.

**Comment by Portponky** [comment] 2024-03-24 23:29
Closing, can't reproduce and I've used it with 4.3d4 without issue.

**Closed by Portponky** 2024-03-24 23:29 UTC
