### ISSUE TITLE
Changes to terrain are not being saved (4.3)

### ISSUE THREAD

**Issue by timoohr** [Portponky/better-terrain#92] opened 2024-07-01 20:11 UTC
First of all let me thank you for this amazing plugin. It's such a massive improvement over the default implementation that I think they should just replace it with yours :)

That said, there seems to be a bit of an issue when it comes to saving the terrain data. I'm using the `tile-map-layer` branch with Godot 4.3.beta2 and the new TileMapLayer node. Went ahead and set up a few dozen terrains yesterday, but after opening the project again today most of them seem to be gone, which, needless to say, was a bit of a bummer.

After digging around a bit, it does seem indeed that Godot seems pretty reluctant to save any changes made to the terrains to the tileset file when pressing CTRL+S. Usually requires changing some other settings in the tileset (like margins or something) to get it to do so.

**Comment by the-old-one** [comment] 2024-07-04 09:14
I've noticed that as well in 4.3 and I'm not sure if it's an issue of Godot or the plugin. For now the TileSet itself has a Save option in the menu which works reliably.
<img width="395" alt="Screenshot 2024-07-04 190813" src="https://github.com/Portponky/better-terrain/assets/3480944/d60abc6f-8333-4ffe-ae88-575796a71581">

**Comment by Portponky** [comment] 2024-07-07 14:31
Hi, yes, this is a Godot bug or quirk. I've not been able to narrow down the cause, but it's something to do with setting metadata on a TileData object in a resource. Sometimes it marks it as a change that can be saved, other times it does not.

**Comment by Portponky** [comment] 2024-07-21 17:01
Just noticed there's an EditorInterface.mark_scene_as_unsaved, which could help mitigate this.

**Comment by Portponky** [comment] 2024-07-27 11:51
Closed as duplicate of #11 and I think I have a solution for this.

**Closed by Portponky** 2024-07-27 11:51 UTC
